# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Implementing PMMH for the toy SV model.
#'
#' The main cpp-function powering the R wrapper.
#'
#' @param measurements arma::vec providing the measurements (or y or measurements)
#' @param lNumber number of particles
#' @param initVals arma::vec giving the three starting values for phiX,
#'   sigmaX and betaY
#' @return double; value of the log-likelihood estimated via the BPF
#'
#' @export
svModelBpfLogLike <- function(measurements, lNumber, initVals) {
    .Call(`_SVmodelRcppSMC_svModelBpfLogLike`, measurements, lNumber, initVals)
}

#' A function to calculate the log prior for a proposal.
#' 
#' The prior is IG(0.01,0.01).
#'
#' @param proposal a constant reference to proposed values of the parameters
#' 
#' @return the log-prior ratio (part of the PMMH-ratio) to be combined with the
#'   likelihood ratio
NULL

#' Implementing PMMH for the toy SV model.
#'
#' The main cpp-function powering the R wrapper.
#'
#' @param measurements arma::vec providing the measurements (or y or measurements)
#' @param lNumber number of particles
#' @param lMCMCits number of PMMH iterations
#' @param initVals arma::vec giving the three starting values for phiX,
#'   sigmaX and betaY
#' @param rwMHvar standard deviations for the RW-MH proposal step
#' @param numProgressOutputs int giving the number of progress outputs i.e.
#'   if set to 10, then progress output occurs for every additional 10% of 
#'   completion
#' @return Rcpp::List containing the results: parameter samples (sigmaX, 
#'   betaY) and log-prior and log-likelihoood estimates
#'
#' @export
svModelPMMHimpl <- function(measurements, lNumber, lMCMCits, initVals, rwMHvar, numProgressOutputs = 10L) {
    .Call(`_SVmodelRcppSMC_svModelPMMHimpl`, measurements, lNumber, lMCMCits, initVals, rwMHvar, numProgressOutputs)
}

#' A function to sample model parameters from full conditional Gibbs blocks.
#'
#' The model parameters are \code{sigmaX} and \code{betaY}, passed via a 
#' parameter class. The prior is set to \code{IG(0.01,0.01)}
#'
#' @param y an arma::vec of data measurements
#' @param referenceTrajectoryX a std::vector<double> passing the 
#'   reference trajectory
#' @param GibbsParameters a class storing the Gibbs samples
#' @param GibbsPriors a class storing the Gibbs sampler prior settings
#'
#' @return a parameter class 
NULL

#' Implementing PG for the toy SV model.
#'
#' The main cpp-function powering the R wrapper for the PG sampler.
#'
#' @param measurements arma::vec providing the measurements
#' @param lNumber number of particles
#' @param lMCMCits number of PG iterations
#' @param initVals arma::vec giving the three starting values for phiX,
#'   sigmaX and betaY
#' @param initReferenceTrajectory initial reference trajectory values to 
#'   condition on
#' @param numProgressOutputs int giving the number of progress outputs i.e.
#'   if set to 10, then progress output occurs for every additional 10% of 
#'   completion
#' @return Rcpp::List containing the results: parameter samples sigmaX, 
#'   betaY
#'
#' @export
svModelPGimpl <- function(measurements, lNumber, lMCMCits, initVals, initReferenceTrajectory, numProgressOutputs = 10L) {
    .Call(`_SVmodelRcppSMC_svModelPGimpl`, measurements, lNumber, lMCMCits, initVals, initReferenceTrajectory, numProgressOutputs)
}

#' Implementing PMMH for the toy SV model.
#'
#' The main cpp-function powering the R wrapper.
#'
#' @param measurements arma::vec providing the measurements (or y or
#' measurements)
#' @param lNumber number of particles
#' @param initVals arma::vec giving the three starting values for phiX,
#'   sigmaX and betaY
#' @param resampleFreq  frequency at which resampling is performed; if
#'   negative, then resampling is never performed; if between [0,1), then
#'   resampling is performed when  the ESS falls below that proportion of the
#'   number of particles and when it is greater than or equal to 1, resampling
#'   is carried out when the ESS falls below that value (note: if this
#'   parameter is larger than the total number of particles, then resampling
#'   will always be performed!)
#' @return Rcpp::List containing the results: parameter samples (sigmaX, 
#'   betaY) and log-prior and log-likelihoood estimates
#'
#' @export
svModelALtrackingImp <- function(measurements, initVals, lNumber, resampleFreq = 0.5) {
    .Call(`_SVmodelRcppSMC_svModelALtrackingImp`, measurements, initVals, lNumber, resampleFreq)
}

