# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A function to calculate the log prior for a proposal.
#' 
#' The prior is IG(0.01,0.01).
#'
#' @param proposal a constant reference to proposed values of the parameters
#' 
#' @return the log-prior ratio (part of the PMMH-ratio) to be combined with the
#'   likelihood ratio
NULL

#' A function to initialize a particle 
#' 
#' Used implicitly by myMove at the corresponding particle class.
#'
#' @param X a reference to the (empty) particle value
#' @param logweight a reference to the empty particle log weight
#' @param param additional algorithm parameters
#' 
#' @return no return; modify in place
NULL

#' The proposal function.
#' 
#' Used implicitly by myMove at the corresponding particle class.
#' 
#' @param lTim     The sampler iteration.
#' @param X            A reference to the current particle value
#' @param logweight    A reference to the current particle log weight
#' @param param additional algorithm parameters
#' 
#' @return no return; modify in place
NULL

#' Implementing PMMH for the toy SV model.
#'
#' The main cpp-function powering the R wrapper.
#'
#' @param measurements arma::vec providing the measurements (or y or measurements)
#' @param lNumber number of particles
#' @param lMCMCits number of PMMH iterations
#' @param starting_vals arma::vec giving the three starting values for phi_x,
#'   sigma_x and beta_y
#' @param rw_mh_var standard deviations for the RW-MH proposal step
#' @param num_progress_outputs int giving the number of progress outputs i.e.
#'   if set to 10, then progress output occurs for every additional 10% of 
#'   completion
#' @return Rcpp::List containing the results: parameter samples (sigma_x, 
#'   beta_y) and log-prior and log-likelihoood estimates
#'
#' @export
sv_model_pmmh_cpp <- function(measurements, lNumber, lMCMCits, starting_vals, rw_mh_var, num_progress_outputs = 10L) {
    .Call(`_SVmodelExamples_sv_model_pmmh_cpp`, measurements, lNumber, lMCMCits, starting_vals, rw_mh_var, num_progress_outputs)
}

