# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Implementing PMMH for the toy SV model.
#'
#' The main cpp-function powering the R wrapper.
#'
#' @param measurements arma::vec providing the measurements (or y or measurements)
#' @param lNumber number of particles
#' @param starting_vals arma::vec giving the three starting values for phi_x,
#'   sigma_x and beta_y
#' @return double; value of the log-likelihood estimated via the BPF
#'
#' @export
bpf_loglike_sv <- function(measurements, lNumber, starting_vals) {
    .Call(`_SVmodelRcppSMC_bpf_loglike_sv`, measurements, lNumber, starting_vals)
}

#' A function to calculate the log prior for a proposal.
#' 
#' The prior is IG(0.01,0.01).
#'
#' @param proposal a constant reference to proposed values of the parameters
#' 
#' @return the log-prior ratio (part of the PMMH-ratio) to be combined with the
#'   likelihood ratio
NULL

#' Implementing PMMH for the toy SV model.
#'
#' The main cpp-function powering the R wrapper.
#'
#' @param measurements arma::vec providing the measurements (or y or measurements)
#' @param lNumber number of particles
#' @param lMCMCits number of PMMH iterations
#' @param starting_vals arma::vec giving the three starting values for phi_x,
#'   sigma_x and beta_y
#' @param rw_mh_var standard deviations for the RW-MH proposal step
#' @param num_progress_outputs int giving the number of progress outputs i.e.
#'   if set to 10, then progress output occurs for every additional 10% of 
#'   completion
#' @return Rcpp::List containing the results: parameter samples (sigma_x, 
#'   beta_y) and log-prior and log-likelihoood estimates
#'
#' @export
sv_model_pmmh_cpp <- function(measurements, lNumber, lMCMCits, starting_vals, rw_mh_var, num_progress_outputs = 10L) {
    .Call(`_SVmodelRcppSMC_sv_model_pmmh_cpp`, measurements, lNumber, lMCMCits, starting_vals, rw_mh_var, num_progress_outputs)
}

#' Implementing PMMH for the toy SV model.
#'
#' The main cpp-function powering the R wrapper.
#'
#' @param measurements arma::vec providing the measurements (or y or
#' measurements)
#' @param lNumber number of particles
#' @param starting_vals arma::vec giving the three starting values for phi_x,
#'   sigma_x and beta_y
#' @param resampleFreq  frequency at which resampling is performed; if
#'   negative, then resampling is never performed; if between [0,1), then
#'   resampling is performed when  the ESS falls below that proportion of the
#'   number of particles and when it is greater than or equal to 1, resampling
#'   is carried out when the ESS falls below that value (note: if this
#'   parameter is larger than the total number of particles, then resampling
#'   will always be performed!)
#' @return Rcpp::List containing the results: parameter samples (sigma_x, 
#'   beta_y) and log-prior and log-likelihoood estimates
#'
#' @export
sv_model_al_tracking_impl <- function(measurements, starting_vals, lNumber, resampleFreq = 0.5) {
    .Call(`_SVmodelRcppSMC_sv_model_al_tracking_impl`, measurements, starting_vals, lNumber, resampleFreq)
}

